name: Publish MD Files
description: Publishes MD files from GitHub to Confluence
inputs:
  CONF_SPACE:
    description: 'Space of your page'
    required: true
  MD2CF_PARAMS:
    description: Extra parameters
    required: false
  DOC_SPACE:
    description: The Confluence space
    required: true
    

runs:
  using: composite
  steps:

  - 
    name: Checkout code
    uses: actions/checkout@v4

  -
    name: Set up Python 3.12
    uses: actions/setup-python@v4
    with:
      python-version: 3.12

  -
    name: Install the library
    shell: bash
    run: |
      python3 -m venv .venv
      source .venv/bin/activate
  -
    name: Install Library
    shell: bash
    run: python3 -m pip install md2cf
  
  -
    name: Publish Docs
    shell: bash
    run: md2cf --host 'https://confluence.minyma.io/rest/api' --token '${{ inputs.CONFLUENCE_API_TOKEN }}' --space ${{ inputs.CONF_SPACE }} ${{ inputs.MD2CF_PARAMS }} ${{ inputs.DOC_SPACE }}

